
 const CartActionTypes={
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_TO_CART:"ADD_TO_CART",
    DELETE_ITEM:"DELETE_ITEM",
    DECREASE_QUANTITY:"DECREASE_QUANTITY"
}
export default CartActionTypes